apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: avalanche
  name: avalanche
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: http-avalanche
  jobLabel: k8s-avalanche
  namespaceSelector:
    matchNames:
    - avalanche
  selector:
    matchLabels:
      app: pg-avalanche
